import Head from "next/head";
import AboutSection from "../components/AboutSection";
import { ContactSection } from "../components/ContactSection";
import EducationSection from "../components/EducationSection";
import ExperienceSection from "../components/ExperienceSection";
import Footer from "../components/Footer";
import HeroBanner from "../components/HeroBanner";
import NavBar from "../components/NavBar";
import ProjectCards from "../components/ProjectCards";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="overflow-x-hidden">
        <NavBar />
        <HeroBanner />
        <AboutSection />
        <ExperienceSection />
        <EducationSection />
        <ProjectCards />
        <ContactSection />
        <Footer />
      </main>
    </div>
  );
}
